# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20160324_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='summary',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='url_address',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='user',
        ),
    ]
