# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20160324_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='url_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
