# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_remove_todotask_url_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='created_date',
        ),
        migrations.AddField(
            model_name='todotask',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
